import { ToolDefinition } from "./types";

export const TOOLS_REGISTRY: ToolDefinition[] = [
  {
    id: "image-compressor",
    slug: "image-compressor",
    name: "Compress Image",
    shortName: "Compress Image",
    category: "image",
    toolType: "compressor",
    tags: ["compress", "image", "jpg", "png", "webp", "size", "reduce"],
    componentKey: "CompressImageTool",
    processingMode: "client",
    inputTypes: ["image/jpeg", "image/png", "image/webp"],
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputTypes: ["image/jpeg", "image/png", "image/webp"],
    outputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    title: "JPEG Compressor to 200KB - Free, Fast & Private | Cluster Tools",
    description: "Use our free JPEG compressor to 200KB. Reduce image file size instantly in your browser. No signup, 100% private, and fast.",
    keywords: ["jpeg compressor to 200kb", "compress jpeg to 200kb online", "reduce jpeg file size to 200kb", "jpg compressor 200kb free", "how to compress image to 200kb", "jpeg to 200kb converter"],
    aliases: ["image compressor", "jpg compressor", "jpeg compressor to 200kb"],
    searchTerms: ["compress", "shrink", "reduce", "size", "kb", "mb", "image", "200kb"],
    popular: true,
    status: "live",
    lastModified: "2026-08-27T00:00:00.000Z",
    faqs: [
      {
        question: "How do I compress a JPEG to under 200KB?",
        answer: "Simply upload your image, select 'Target Size', type '200' in the KB field, and the tool will automatically find the best quality setting to hit your goal."
      },
      {
        question: "Does compressing a JPEG to 200KB reduce image quality?",
        answer: "The visual difference is typically unnoticeable to the human eye, especially for web use. Our JPEG compressor to 200KB removes redundant data while preserving visual fidelity."
      },
      {
        question: "Is this JPEG to 200KB converter really free?",
        answer: "Yes, it is completely free to use with no sign-ups or artificial limits. Because it runs locally in your browser, we have no server costs to pass on to you."
      },
      {
        question: "How fast is it to reduce JPEG file size to 200KB?",
        answer: "It takes just a few milliseconds. The tool runs a fast binary search algorithm locally on your device to instantly find the optimal quality setting."
      },
      {
        question: "Do you store my compressed images?",
        answer: "No. Processing happens entirely on your device in real-time. We do not have servers to store your images."
      },
      {
        question: "Can I compress multiple images at once?",
        answer: "Yes, you can drop as many images as you like into the tool. Once processed, you can download them all together in a single ZIP file."
      }
    ],
  },
  {
    id: "image-cropper",
    slug: "image-cropper",
    name: "Image Cropper",
    shortName: "Crop",
    category: "image",
    toolType: "editor",
    tags: ["crop", "image", "cut", "trim", "aspect ratio"],
    componentKey: "ImageCropperTool",
    processingMode: "client",
    inputTypes: ["image/jpeg", "image/png", "image/webp"],
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputTypes: ["image/jpeg", "image/png", "image/webp"],
    outputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    title: "Crop Image Online, Free & Private | Cluster Tools",
    description: "Crop your images instantly in your browser. No upload, free, and private.",
    keywords: ["crop image", "crop photo", "cut image", "image cropper online"],
    aliases: ["image cropper", "photo cropper"],
    searchTerms: ["crop", "cut", "trim", "aspect", "ratio", "image"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "jpg-to-pdf",
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    shortName: "JPG → PDF",
    category: "pdf",
    toolType: "converter",
    tags: ["jpg", "pdf", "convert", "image to pdf"],
    componentKey: "JpgToPdfTool",
    processingMode: "client",
    inputTypes: ["image/jpeg", "image/png", "image/webp"],
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputTypes: ["application/pdf"],
    outputFormats: [".pdf"],
    title: "Convert JPG to PDF Online, Free & Private | Cluster Tools",
    description: "Convert JPG images to a single PDF document entirely in your browser. Fast, private, and secure.",
    keywords: ["jpg to pdf", "convert jpg to pdf", "image to pdf", "combine images to pdf"],
    aliases: ["image to pdf converter", "jpg to pdf converter"],
    searchTerms: ["convert", "jpg", "pdf", "image", "combine"],
    popular: true,
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "jpg-to-png",
    slug: "jpg-to-png",
    name: "JPG to PNG",
    shortName: "JPG → PNG",
    category: "image",
    toolType: "converter",
    tags: ["jpg", "png", "convert", "image"],
    componentKey: "JpgToPngTool",
    processingMode: "client",
    inputTypes: ["image/jpeg"],
    inputFormats: [".jpg", ".jpeg"],
    outputTypes: ["image/png"],
    outputFormats: [".png"],
    title: "Convert JPG to PNG Online, Free & Private | Cluster Tools",
    description: "Convert JPG images to PNG format instantly in your browser.",
    keywords: ["jpg to png", "convert jpg to png", "image format converter"],
    aliases: ["jpg to png converter"],
    searchTerms: ["convert", "jpg", "png", "image"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "png-to-jpg",
    slug: "png-to-jpg",
    name: "PNG to JPG",
    shortName: "PNG → JPG",
    category: "image",
    toolType: "converter",
    tags: ["png", "jpg", "convert", "image"],
    componentKey: "PngToJpgTool",
    processingMode: "client",
    inputTypes: ["image/png"],
    inputFormats: [".png"],
    outputTypes: ["image/jpeg"],
    outputFormats: [".jpg", ".jpeg"],
    title: "Convert PNG to JPG Online, Free & Private | Cluster Tools",
    description: "Convert PNG images to JPG format instantly in your browser.",
    keywords: ["png to jpg", "convert png to jpg", "image format converter"],
    aliases: ["png to jpg converter"],
    searchTerms: ["convert", "png", "jpg", "image"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "pdf-to-jpg",
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    shortName: "PDF → JPG",
    category: "pdf",
    toolType: "converter",
    tags: ["pdf", "jpg", "convert", "extract"],
    componentKey: "PdfToJpgTool",
    processingMode: "client",
    inputTypes: ["application/pdf"],
    inputFormats: [".pdf"],
    outputTypes: ["image/jpeg"],
    outputFormats: [".jpg", ".jpeg"],
    title: "Convert PDF to JPG Online, Free & Private | Cluster Tools",
    description: "Extract pages from a PDF as JPG images directly in your browser.",
    keywords: ["pdf to jpg", "convert pdf to jpg", "extract images from pdf"],
    aliases: ["pdf to image converter", "pdf to jpg converter"],
    searchTerms: ["convert", "pdf", "jpg", "extract", "pages"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "image-resizer",
    slug: "image-resizer",
    name: "Resize Image",
    shortName: "Resize",
    category: "image",
    toolType: "editor",
    tags: ["resize", "image", "dimensions", "scale", "width", "height"],
    componentKey: "ResizeImageTool",
    processingMode: "client",
    inputTypes: ["image/jpeg", "image/png", "image/webp"],
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputTypes: ["image/jpeg", "image/png", "image/webp"],
    outputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    title: "Resize Image Online, Free & Private | Cluster Tools",
    description: "Change image dimensions instantly in your browser. Free and private.",
    keywords: ["resize image", "change image dimensions", "scale image online"],
    aliases: ["image resizer"],
    searchTerms: ["resize", "scale", "dimensions", "width", "height", "image"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "compress-pdf",
    slug: "compress-pdf",
    name: "Compress PDF",
    shortName: "Compress PDF",
    category: "pdf",
    toolType: "compressor",
    tags: ["compress", "pdf", "size", "reduce"],
    componentKey: "CompressPdfTool",
    processingMode: "client",
    inputTypes: ["application/pdf"],
    inputFormats: [".pdf"],
    outputTypes: ["application/pdf"],
    outputFormats: [".pdf"],
    title: "Compress PDF Online, Free & Private | Cluster Tools",
    description: "Reduce PDF file size securely in your browser. No upload, free, and private structural optimization.",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf", "pdf compressor online"],
    aliases: ["pdf compressor"],
    searchTerms: ["compress", "shrink", "reduce", "size", "kb", "mb", "pdf"],
    popular: true,
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "merge-pdf",
    slug: "merge-pdf",
    name: "Merge PDF",
    shortName: "Merge",
    category: "pdf",
    toolType: "editor",
    tags: ["merge", "pdf", "combine", "join"],
    componentKey: "MergePdfTool",
    processingMode: "client",
    inputTypes: ["application/pdf"],
    inputFormats: [".pdf"],
    outputTypes: ["application/pdf"],
    outputFormats: [".pdf"],
    title: "Merge PDF Files Online, Free & Private | Cluster Tools",
    description: "Combine multiple PDFs into a single document entirely in your browser. Fast, private, and secure.",
    keywords: ["merge pdf", "combine pdf files", "join pdf", "pdf merger online"],
    aliases: ["pdf merger", "combine pdf"],
    searchTerms: ["merge", "combine", "join", "pdf"],
    popular: true,
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "percentage-calculator",
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    shortName: "Percentage",
    category: "calculators",
    toolType: "calculator",
    tags: ["percentage", "math", "calculator", "percent"],
    componentKey: "PercentageCalculatorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Percentage Calculator Online | Cluster Tools",
    description: "Calculate percentages, percentage increases, and percentage differences easily and accurately.",
    keywords: ["percentage calculator", "percent calculator", "calculate percentage", "percentage increase"],
    aliases: ["percent calculator"],
    searchTerms: ["percentage", "percent", "calculator", "math", "increase", "decrease"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "age-calculator",
    slug: "age-calculator",
    name: "Age Calculator",
    shortName: "Age",
    category: "calculators",
    toolType: "calculator",
    tags: ["age", "date", "calculator", "birthday"],
    componentKey: "AgeCalculatorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Age Calculator Online | Cluster Tools",
    description: "Calculate your exact age in years, months, and days based on your date of birth.",
    keywords: ["age calculator", "calculate age", "birthday calculator", "date difference"],
    aliases: ["birthday calculator"],
    searchTerms: ["age", "calculator", "birthday", "date", "years", "months", "days"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "word-counter",
    slug: "word-counter",
    name: "Word Counter",
    shortName: "Words",
    category: "text",
    toolType: "analyzer",
    tags: ["word", "count", "characters", "text", "analyzer"],
    componentKey: "WordCounterTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Word & Character Counter Online | Cluster Tools",
    description: "Count words, characters, sentences, and paragraphs in real-time. Fast, free, and private text analysis.",
    keywords: ["word counter", "character counter", "text analyzer", "count words online"],
    aliases: ["character counter", "text counter"],
    searchTerms: ["word", "counter", "character", "text", "sentences", "paragraphs"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "json-formatter",
    slug: "json-formatter",
    name: "JSON Formatter",
    shortName: "JSON",
    category: "developer",
    toolType: "formatter",
    tags: ["json", "format", "beautify", "minify", "developer"],
    componentKey: "JsonFormatterTool",
    processingMode: "client",
    inputTypes: ["application/json"],
    inputFormats: [".json"],
    outputTypes: ["application/json"],
    outputFormats: [".json"],
    title: "JSON Formatter & Validator Online | Cluster Tools",
    description: "Format, beautify, validate, and minify JSON data directly in your browser. Secure and fast.",
    keywords: ["json formatter", "json beautifier", "json validator", "format json online"],
    aliases: ["json beautifier", "json validator"],
    searchTerms: ["json", "format", "beautify", "validate", "minify", "developer"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "webp-to-jpg",
    slug: "webp-to-jpg",
    name: "WebP to JPG",
    shortName: "WebP → JPG",
    category: "image",
    toolType: "converter",
    tags: ["webp", "jpg", "convert", "image"],
    componentKey: "WebpToJpgTool",
    processingMode: "client",
    inputTypes: ["image/webp"],
    inputFormats: [".webp"],
    outputTypes: ["image/jpeg"],
    outputFormats: [".jpg", ".jpeg"],
    title: "Convert WebP to JPG Online, Free & Private | Cluster Tools",
    description: "Convert WebP images to JPG format instantly in your browser.",
    keywords: ["webp to jpg", "convert webp to jpg", "image format converter"],
    aliases: ["webp to jpg converter"],
    searchTerms: ["convert", "webp", "jpg", "image"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "heic-to-jpg",
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    shortName: "HEIC → JPG",
    category: "image",
    toolType: "converter",
    tags: ["heic", "jpg", "convert", "image", "iphone"],
    componentKey: "HeicToJpgTool",
    processingMode: "client",
    inputTypes: ["image/heic", "image/heif"],
    inputFormats: [".heic", ".heif"],
    outputTypes: ["image/jpeg"],
    outputFormats: [".jpg", ".jpeg"],
    title: "Convert HEIC to JPG Online, Free & Private | Cluster Tools",
    description: "Convert iPhone HEIC photos to standard JPG format entirely in your browser.",
    keywords: ["heic to jpg", "convert heic to jpg", "iphone photo converter"],
    aliases: ["heic to jpg converter"],
    searchTerms: ["convert", "heic", "jpg", "image", "iphone", "photo"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "split-pdf",
    slug: "split-pdf",
    name: "Split PDF",
    shortName: "Split",
    category: "pdf",
    toolType: "editor",
    tags: ["split", "pdf", "extract", "pages"],
    componentKey: "SplitPdfTool",
    processingMode: "client",
    inputTypes: ["application/pdf"],
    inputFormats: [".pdf"],
    outputTypes: ["application/pdf", "application/zip"],
    outputFormats: [".pdf", ".zip"],
    title: "Split PDF Files Online, Free & Private | Cluster Tools",
    description: "Split PDF files into individual pages or extract specific pages entirely in your browser.",
    keywords: ["split pdf", "extract pdf pages", "separate pdf pages"],
    aliases: ["pdf splitter"],
    searchTerms: ["split", "extract", "separate", "pages", "pdf"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "rotate-pdf",
    slug: "rotate-pdf",
    name: "Rotate PDF",
    shortName: "Rotate",
    category: "pdf",
    toolType: "editor",
    tags: ["rotate", "pdf", "turn", "orientation"],
    componentKey: "RotatePdfTool",
    processingMode: "client",
    inputTypes: ["application/pdf"],
    inputFormats: [".pdf"],
    outputTypes: ["application/pdf"],
    outputFormats: [".pdf"],
    title: "Rotate PDF Pages Online, Free & Private | Cluster Tools",
    description: "Rotate individual PDF pages or entire documents instantly in your browser.",
    keywords: ["rotate pdf", "turn pdf pages", "fix pdf orientation"],
    aliases: ["pdf rotator"],
    searchTerms: ["rotate", "turn", "orientation", "pdf", "pages"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "loan-calculator",
    slug: "loan-calculator",
    name: "Loan Calculator",
    shortName: "Loan",
    category: "calculators",
    toolType: "calculator",
    tags: ["loan", "finance", "calculator", "interest", "payment"],
    componentKey: "LoanCalculatorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Loan Calculator Online | Cluster Tools",
    description: "Calculate loan payments, total interest, and payoff schedules instantly.",
    keywords: ["loan calculator", "payment calculator", "interest calculator"],
    aliases: ["personal loan calculator"],
    searchTerms: ["loan", "calculator", "finance", "interest", "payment", "amortization"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "mortgage-calculator",
    slug: "mortgage-calculator",
    name: "Mortgage Calculator",
    shortName: "Mortgage",
    category: "calculators",
    toolType: "calculator",
    tags: ["mortgage", "finance", "calculator", "house", "interest", "payment"],
    componentKey: "MortgageCalculatorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Mortgage Calculator Online | Cluster Tools",
    description: "Calculate your monthly mortgage payments and total interest easily.",
    keywords: ["mortgage calculator", "home loan calculator", "house payment calculator"],
    aliases: ["home loan calculator"],
    searchTerms: ["mortgage", "calculator", "finance", "interest", "payment", "house", "home"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "discount-calculator",
    slug: "discount-calculator",
    name: "Discount Calculator",
    shortName: "Discount",
    category: "calculators",
    toolType: "calculator",
    tags: ["discount", "sale", "calculator", "savings", "percent"],
    componentKey: "DiscountCalculatorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Discount & Sale Calculator Online | Cluster Tools",
    description: "Calculate discounts, sale prices, and your total savings instantly.",
    keywords: ["discount calculator", "sale calculator", "price after discount"],
    aliases: ["sale calculator", "percent off calculator"],
    searchTerms: ["discount", "calculator", "sale", "savings", "percent", "off", "price"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "png-to-webp",
    slug: "png-to-webp",
    name: "PNG to WebP",
    shortName: "PNG → WebP",
    category: "image",
    toolType: "converter",
    tags: ["png", "webp", "convert", "image"],
    componentKey: "PngToWebpTool",
    processingMode: "client",
    inputTypes: ["image/png"],
    inputFormats: [".png"],
    outputTypes: ["image/webp"],
    outputFormats: [".webp"],
    title: "Convert PNG to WebP Online, Free & Private | Cluster Tools",
    description: "Convert PNG images to WebP format instantly in your browser while preserving transparency.",
    keywords: ["png to webp", "convert png to webp", "image format converter"],
    aliases: ["png to webp converter"],
    searchTerms: ["convert", "png", "webp", "image"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "jpg-to-webp",
    slug: "jpg-to-webp",
    name: "JPG to WebP",
    shortName: "JPG → WebP",
    category: "image",
    toolType: "converter",
    tags: ["jpg", "webp", "convert", "image"],
    componentKey: "JpgToWebpTool",
    processingMode: "client",
    inputTypes: ["image/jpeg"],
    inputFormats: [".jpg", ".jpeg"],
    outputTypes: ["image/webp"],
    outputFormats: [".webp"],
    title: "Convert JPG to WebP Online, Free & Private | Cluster Tools",
    description: "Convert JPG images to WebP format instantly in your browser.",
    keywords: ["jpg to webp", "convert jpg to webp", "image format converter"],
    aliases: ["jpg to webp converter"],
    searchTerms: ["convert", "jpg", "webp", "image"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "image-to-pdf",
    slug: "image-to-pdf",
    name: "Image to PDF",
    shortName: "Image → PDF",
    category: "pdf",
    toolType: "converter",
    tags: ["image", "pdf", "convert"],
    componentKey: "ImageToPdfTool",
    processingMode: "client",
    inputTypes: ["image/jpeg", "image/png", "image/webp"],
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputTypes: ["application/pdf"],
    outputFormats: [".pdf"],
    title: "Convert Images to PDF Online, Free & Private | Cluster Tools",
    description: "Convert multiple images to a single PDF document entirely in your browser.",
    keywords: ["image to pdf", "convert image to pdf", "combine images to pdf"],
    aliases: ["image to pdf converter"],
    searchTerms: ["convert", "image", "pdf", "combine"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "extract-pdf-pages",
    slug: "extract-pdf-pages",
    name: "Extract PDF Pages",
    shortName: "Extract",
    category: "pdf",
    toolType: "editor",
    tags: ["extract", "pdf", "pages"],
    componentKey: "ExtractPdfPagesTool",
    processingMode: "client",
    inputTypes: ["application/pdf"],
    inputFormats: [".pdf"],
    outputTypes: ["application/pdf"],
    outputFormats: [".pdf"],
    title: "Extract PDF Pages Online, Free & Private | Cluster Tools",
    description: "Extract specific pages from a PDF document directly in your browser.",
    keywords: ["extract pdf pages", "save pdf pages"],
    aliases: ["pdf page extractor"],
    searchTerms: ["extract", "pages", "pdf", "split"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "delete-pdf-pages",
    slug: "delete-pdf-pages",
    name: "Delete PDF Pages",
    shortName: "Delete",
    category: "pdf",
    toolType: "editor",
    tags: ["delete", "pdf", "pages", "remove"],
    componentKey: "DeletePdfPagesTool",
    processingMode: "client",
    inputTypes: ["application/pdf"],
    inputFormats: [".pdf"],
    outputTypes: ["application/pdf"],
    outputFormats: [".pdf"],
    title: "Delete PDF Pages Online, Free & Private | Cluster Tools",
    description: "Remove specific pages from a PDF document instantly in your browser.",
    keywords: ["delete pdf pages", "remove pdf pages"],
    aliases: ["pdf page remover"],
    searchTerms: ["delete", "remove", "pages", "pdf"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "pdf-page-counter",
    slug: "pdf-page-counter",
    name: "PDF Page Counter",
    shortName: "Count Pages",
    category: "pdf",
    toolType: "analyzer",
    tags: ["count", "pdf", "pages", "analyzer"],
    componentKey: "PdfPageCounterTool",
    processingMode: "client",
    inputTypes: ["application/pdf"],
    inputFormats: [".pdf"],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Count PDF Pages Online | Cluster Tools",
    description: "Quickly count the number of pages in multiple PDF documents simultaneously.",
    keywords: ["pdf page counter", "count pdf pages"],
    aliases: ["pdf page count"],
    searchTerms: ["count", "pages", "pdf", "number"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "pdf-metadata-viewer",
    slug: "pdf-metadata-viewer",
    name: "PDF Metadata Viewer",
    shortName: "Metadata",
    category: "pdf",
    toolType: "analyzer",
    tags: ["metadata", "pdf", "properties", "viewer"],
    componentKey: "PdfMetadataViewerTool",
    processingMode: "client",
    inputTypes: ["application/pdf"],
    inputFormats: [".pdf"],
    outputTypes: ["application/json"],
    outputFormats: [".json"],
    title: "View PDF Metadata Online | Cluster Tools",
    description: "View properties and metadata hidden inside your PDF documents.",
    keywords: ["pdf metadata viewer", "view pdf properties"],
    aliases: ["pdf properties viewer"],
    searchTerms: ["metadata", "properties", "pdf", "viewer", "info"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "compound-interest-calculator",
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    shortName: "Compound",
    category: "calculators",
    toolType: "calculator",
    tags: ["compound", "interest", "finance", "calculator", "investment"],
    componentKey: "CompoundInterestCalculatorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Compound Interest Calculator Online | Cluster Tools",
    description: "Calculate compound interest to forecast your investment growth.",
    keywords: ["compound interest calculator", "investment calculator"],
    aliases: ["investment calculator"],
    searchTerms: ["compound", "interest", "finance", "calculator", "investment", "growth"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "roi-calculator",
    slug: "roi-calculator",
    name: "ROI Calculator",
    shortName: "ROI",
    category: "calculators",
    toolType: "calculator",
    tags: ["roi", "finance", "calculator", "investment", "return"],
    componentKey: "RoiCalculatorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "ROI Calculator Online | Cluster Tools",
    description: "Calculate Return on Investment (ROI) for any business or investment.",
    keywords: ["roi calculator", "return on investment calculator"],
    aliases: ["return on investment calculator"],
    searchTerms: ["roi", "finance", "calculator", "investment", "return", "profit"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "profit-margin-calculator",
    slug: "profit-margin-calculator",
    name: "Profit Margin Calculator",
    shortName: "Profit Margin",
    category: "calculators",
    toolType: "calculator",
    tags: ["profit", "margin", "finance", "calculator", "business"],
    componentKey: "ProfitMarginCalculatorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Profit Margin Calculator Online | Cluster Tools",
    description: "Calculate gross profit margin, markup, and gross profit for your business.",
    keywords: ["profit margin calculator", "margin calculator", "markup calculator"],
    aliases: ["margin calculator", "markup calculator"],
    searchTerms: ["profit", "margin", "finance", "calculator", "business", "markup"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "character-counter",
    slug: "character-counter",
    name: "Character Counter",
    shortName: "Characters",
    category: "text",
    toolType: "analyzer",
    tags: ["character", "count", "text", "analyzer"],
    componentKey: "CharacterCounterTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Character Counter Online | Cluster Tools",
    description: "Accurately count characters, graphemes, and lines. Handles emojis and Unicode perfectly.",
    keywords: ["character counter", "count characters", "letter counter"],
    aliases: ["letter counter"],
    searchTerms: ["character", "count", "letters", "text", "length", "emoji"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "case-converter",
    slug: "case-converter",
    name: "Case Converter",
    shortName: "Case Converter",
    category: "text",
    toolType: "editor",
    tags: ["case", "convert", "uppercase", "lowercase", "text"],
    componentKey: "CaseConverterTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Case Converter Online | Cluster Tools",
    description: "Convert text between UPPERCASE, lowercase, Title Case, and Sentence case instantly.",
    keywords: ["case converter", "uppercase converter", "lowercase converter", "title case generator"],
    aliases: ["change text case", "uppercase to lowercase"],
    searchTerms: ["case", "convert", "upper", "lower", "title", "sentence", "text", "capitalize"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "remove-duplicate-lines",
    slug: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    shortName: "Remove Duplicates",
    category: "text",
    toolType: "editor",
    tags: ["duplicate", "lines", "remove", "clean", "list"],
    componentKey: "RemoveDuplicateLinesTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Remove Duplicate Lines Online | Cluster Tools",
    description: "Clean lists and text by safely removing duplicate lines while preserving original order.",
    keywords: ["remove duplicate lines", "delete duplicate lines", "unique list generator"],
    aliases: ["duplicate line remover", "list cleaner"],
    searchTerms: ["duplicate", "lines", "remove", "clean", "list", "unique", "text"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "text-diff-checker",
    slug: "text-diff-checker",
    name: "Text Diff Checker",
    shortName: "Diff Checker",
    category: "text",
    toolType: "analyzer",
    tags: ["diff", "compare", "text", "difference"],
    componentKey: "TextDiffCheckerTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Text Diff Checker Online | Cluster Tools",
    description: "Compare two texts side-by-side to find additions, removals, and changes instantly.",
    keywords: ["text diff", "diff checker", "compare text", "find differences in text"],
    aliases: ["text comparator", "difference checker"],
    searchTerms: ["diff", "compare", "difference", "text", "changes", "compare texts"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "json-validator",
    slug: "json-validator",
    name: "JSON Validator",
    shortName: "JSON Validator",
    category: "developer",
    toolType: "analyzer",
    tags: ["json", "validate", "syntax", "developer", "lint"],
    componentKey: "JsonValidatorTool",
    processingMode: "client",
    inputTypes: ["application/json"],
    inputFormats: [".json"],
    outputTypes: ["application/json"],
    outputFormats: [".json"],
    title: "JSON Validator Online | Cluster Tools",
    description: "Instantly validate JSON data to find syntax errors. 100% private in-browser validation.",
    keywords: ["json validator", "validate json", "json syntax checker", "json linter"],
    aliases: ["json checker", "json linter"],
    searchTerms: ["json", "validate", "check", "syntax", "error", "developer", "lint"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "json-minifier",
    slug: "json-minifier",
    name: "JSON Minifier",
    shortName: "JSON Minifier",
    category: "developer",
    toolType: "formatter",
    tags: ["json", "minify", "compress", "developer"],
    componentKey: "JsonMinifierTool",
    processingMode: "client",
    inputTypes: ["application/json"],
    inputFormats: [".json"],
    outputTypes: ["application/json"],
    outputFormats: [".json"],
    title: "JSON Minifier Online | Cluster Tools",
    description: "Compress JSON data by removing unnecessary whitespace and formatting securely.",
    keywords: ["json minifier", "minify json", "compress json", "json compact"],
    aliases: ["json compressor", "json unformatter"],
    searchTerms: ["json", "minify", "compress", "shrink", "developer", "format"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "base64-encoder-decoder",
    slug: "base64-encoder-decoder",
    name: "Base64 Encoder & Decoder",
    shortName: "Base64",
    category: "developer",
    toolType: "converter",
    tags: ["base64", "encode", "decode", "developer"],
    componentKey: "Base64EncoderDecoderTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Base64 Encoder & Decoder Online | Cluster Tools",
    description: "Encode text to Base64 or decode Base64 back to text with full Unicode support.",
    keywords: ["base64 encoder", "base64 decoder", "encode to base64", "decode base64"],
    aliases: ["base64 tool", "base64 converter"],
    searchTerms: ["base64", "encode", "decode", "developer", "convert", "text"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "url-encoder-decoder",
    slug: "url-encoder-decoder",
    name: "URL Encoder & Decoder",
    shortName: "URL Encoder",
    category: "developer",
    toolType: "converter",
    tags: ["url", "encode", "decode", "percent", "developer"],
    componentKey: "UrlEncoderDecoderTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "URL Encoder & Decoder Online | Cluster Tools",
    description: "Encode URLs safely or decode percent-encoded strings directly in your browser.",
    keywords: ["url encoder", "url decoder", "percent encoding", "url escape"],
    aliases: ["url escape tool", "percent encoder"],
    searchTerms: ["url", "encode", "decode", "percent", "developer", "link", "escape"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  // ─── Batch 5: SEO Tools ────────────────────────────────────────────────────
  {
    id: "meta-tag-generator",
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    shortName: "Meta Tags",
    category: "seo",
    toolType: "generator",
    tags: ["meta tags", "seo", "open graph", "twitter card", "html"],
    componentKey: "MetaTagGeneratorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/html"],
    outputFormats: [],
    title: "Meta Tag Generator — SEO, Open Graph & Twitter Card | Cluster Tools",
    description: "Generate SEO meta tags, Open Graph, and Twitter Card HTML markup for any web page. Free, private, no signup.",
    keywords: ["meta tag generator", "seo meta tags", "open graph generator", "twitter card generator"],
    aliases: ["meta tags tool", "html meta generator"],
    searchTerms: ["meta", "seo", "open graph", "twitter card", "html", "tags"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
    faqs: [
      { question: "Do meta tags guarantee better rankings?", answer: "No. Meta tags provide signals to search engines and social platforms, but rankings depend on many other factors including content quality and backlinks." },
      { question: "Is my page content sent anywhere?", answer: "No. All generation happens in your browser. Nothing is transmitted." }
    ],
  },
  {
    id: "robots-txt-generator",
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    shortName: "Robots.txt",
    category: "seo",
    toolType: "generator",
    tags: ["robots.txt", "seo", "crawlers", "disallow", "allow"],
    componentKey: "RobotsTxtGeneratorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [".txt"],
    title: "Robots.txt Generator — Custom Crawl Rules | Cluster Tools",
    description: "Generate a valid robots.txt file with custom User-agent, Allow/Disallow rules, and Sitemap URL. Free and private.",
    keywords: ["robots.txt generator", "create robots.txt", "seo crawl rules", "disallow crawlers"],
    aliases: ["robots file generator", "crawler rules generator"],
    searchTerms: ["robots", "txt", "crawl", "disallow", "allow", "sitemap", "seo"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "xml-sitemap-generator",
    slug: "xml-sitemap-generator",
    name: "XML Sitemap Generator",
    shortName: "Sitemap",
    category: "seo",
    toolType: "generator",
    tags: ["xml sitemap", "seo", "sitemap.xml", "urls", "indexing"],
    componentKey: "XmlSitemapGeneratorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["application/xml"],
    outputFormats: [".xml"],
    title: "XML Sitemap Generator — Free & Private | Cluster Tools",
    description: "Generate a valid XML sitemap with custom URLs, last-modified dates, change frequencies, and priority values.",
    keywords: ["xml sitemap generator", "create sitemap", "sitemap.xml", "seo sitemap"],
    aliases: ["sitemap creator", "sitemap builder"],
    searchTerms: ["sitemap", "xml", "seo", "urls", "indexing", "google search console"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "seo-snippet-preview",
    slug: "seo-snippet-preview",
    name: "SEO Snippet Preview",
    shortName: "Snippet Preview",
    category: "seo",
    toolType: "preview",
    tags: ["seo", "snippet", "google preview", "serp", "title", "description"],
    componentKey: "SeoSnippetPreviewTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: [],
    outputFormats: [],
    title: "SEO Snippet Preview — Google Search Result Preview | Cluster Tools",
    description: "Preview how your page title and meta description appear in Google-style search results. Instant, browser-based, no upload.",
    keywords: ["seo snippet preview", "google search preview", "serp preview", "meta description preview"],
    aliases: ["search snippet preview", "serp snippet tool"],
    searchTerms: ["snippet", "preview", "google", "serp", "seo", "title", "description", "search result"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "keyword-density-checker",
    slug: "keyword-density-checker",
    name: "Keyword Density Checker",
    shortName: "Keyword Density",
    category: "seo",
    toolType: "analyzer",
    tags: ["keyword density", "seo", "keyword analysis", "content analysis"],
    componentKey: "KeywordDensityCheckerTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: [],
    outputFormats: [],
    title: "Keyword Density Checker — Free & Private | Cluster Tools",
    description: "Calculate keyword density in your text. Count occurrences, total words, and density percentage. All processing local.",
    keywords: ["keyword density checker", "keyword density calculator", "seo keyword analysis", "content keyword density"],
    aliases: ["keyword frequency checker", "keyword analyzer"],
    searchTerms: ["keyword", "density", "frequency", "seo", "content", "analysis", "checker"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "slug-generator",
    slug: "slug-generator",
    name: "Slug Generator",
    shortName: "Slug",
    category: "seo",
    toolType: "converter",
    tags: ["slug", "url slug", "seo", "url friendly", "permalink"],
    componentKey: "SlugGeneratorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "URL Slug Generator — Clean URL Slugs | Cluster Tools",
    description: "Convert any text into clean, URL-friendly slugs for blog posts, page titles, and permalinks. Handles accented Latin characters.",
    keywords: ["slug generator", "url slug", "permalink generator", "seo url slug"],
    aliases: ["url slug creator", "permalink slug tool"],
    searchTerms: ["slug", "url", "permalink", "seo", "friendly", "convert", "text"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  // ─── Batch 5: General Tools ────────────────────────────────────────────────
  {
    id: "qr-code-generator",
    slug: "qr-code-generator",
    name: "QR Code Generator",
    shortName: "QR Code",
    category: "general",
    toolType: "generator",
    tags: ["qr code", "qr generator", "barcode", "url", "text"],
    componentKey: "QrCodeGeneratorTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["image/png"],
    outputFormats: [".png"],
    title: "QR Code Generator — Free, Private & Offline | Cluster Tools",
    description: "Generate QR codes entirely in your browser. No upload, no tracking. Enter any text or URL and download as PNG.",
    keywords: ["qr code generator", "free qr code", "qr code maker", "generate qr code"],
    aliases: ["qr generator", "qrcode maker"],
    searchTerms: ["qr", "code", "barcode", "url", "generate", "download", "scan"],
    popular: true,
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
    faqs: [
      { question: "Is my data sent to a server to generate the QR code?", answer: "No. QR codes are generated entirely on your device using a pure JavaScript algorithm. No data leaves your browser." },
      { question: "What text length is supported?", answer: "This tool supports up to approximately 100 bytes of input for reliable generation across QR versions 1–10." }
    ],
  },
  {
    id: "password-generator",
    slug: "password-generator",
    name: "Password Generator",
    shortName: "Password",
    category: "general",
    toolType: "generator",
    tags: ["password generator", "strong password", "random password", "security"],
    componentKey: "PasswordGeneratorTool",
    processingMode: "client",
    inputTypes: [],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "Password Generator — Cryptographically Strong | Cluster Tools",
    description: "Generate secure, random passwords using your browser's crypto API. Choose length and character sets. Nothing is sent anywhere.",
    keywords: ["password generator", "strong password generator", "random password", "secure password"],
    aliases: ["random password generator", "secure password tool"],
    searchTerms: ["password", "generator", "random", "strong", "secure", "crypto", "characters"],
    popular: true,
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
    faqs: [
      { question: "Are generated passwords transmitted anywhere?", answer: "No. Passwords are generated and stay entirely in your browser. Nothing is sent to any server." },
      { question: "Is Math.random() used?", answer: "No. This tool uses crypto.getRandomValues() which provides cryptographically strong randomness." }
    ],
  },
  {
    id: "uuid-generator",
    slug: "uuid-generator",
    name: "UUID Generator",
    shortName: "UUID",
    category: "general",
    toolType: "generator",
    tags: ["uuid", "guid", "random id", "identifier", "developer"],
    componentKey: "UuidGeneratorTool",
    processingMode: "client",
    inputTypes: [],
    inputFormats: [],
    outputTypes: ["text/plain"],
    outputFormats: [],
    title: "UUID Generator — Version 4 UUIDs | Cluster Tools",
    description: "Generate version 4 UUIDs in your browser using the Web Crypto API. Generate up to 100 at once. No server required.",
    keywords: ["uuid generator", "guid generator", "random uuid", "v4 uuid"],
    aliases: ["guid generator", "unique id generator"],
    searchTerms: ["uuid", "guid", "id", "random", "unique", "identifier", "generate"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
  },
  // ─── Batch 5: Developer Tools ──────────────────────────────────────────────
  {
    id: "jwt-decoder",
    slug: "jwt-decoder",
    name: "JWT Decoder",
    shortName: "JWT",
    category: "developer",
    toolType: "analyzer",
    tags: ["jwt", "json web token", "decode jwt", "developer", "auth"],
    componentKey: "JwtDecoderTool",
    processingMode: "client",
    inputTypes: ["text/plain"],
    inputFormats: [],
    outputTypes: ["application/json"],
    outputFormats: [],
    title: "JWT Decoder — Decode JSON Web Tokens | Cluster Tools",
    description: "Decode JWT header and payload in your browser. Local only — no data is sent anywhere. Signature is NOT verified.",
    keywords: ["jwt decoder", "decode jwt", "json web token decoder", "jwt inspector"],
    aliases: ["jwt parser", "json web token tool"],
    searchTerms: ["jwt", "json web token", "decode", "header", "payload", "auth", "developer"],
    status: "live",
    lastModified: "2026-08-24T00:00:00.000Z",
    faqs: [
      { question: "Does this verify the JWT signature?", answer: "No. This tool only decodes the header and payload for inspection. Signature verification requires the secret or public key, which must be done server-side." },
      { question: "Is my JWT sent to a server?", answer: "No. All decoding happens in your browser using base64url decoding and JSON.parse. Nothing leaves your device." }
    ],
  },

];

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOLS_REGISTRY.find(t => t.id === id);
}

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS_REGISTRY.find(t => t.slug === slug);
}

export function getToolsByCategory(categoryId: string): ToolDefinition[] {
  return TOOLS_REGISTRY.filter(t => t.category === categoryId);
}

export function getAllTools(): ToolDefinition[] {
  return TOOLS_REGISTRY;
}

export function getToolUrl(tool: ToolDefinition): string {
  return `/tools/${tool.category}/${tool.slug}`;
}

